services:
  - type: worker
    name: future-letter-bot
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt --only-binary=:all:
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
